### ISSUE TITLE
Property margin doesn't seem to be configurable

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [fmkra/next-gallery#2]
👋🏼 first off, thanks for the component. It's a huge time saver.

I just wanted to bring up the fact that AFAICT there's no `margin` configuration even though the README docs say so

**Comment by fmkra** [comment]
Thanks for noticing. I'm glad somebody uses this library and finds bugs.

In version `2.0.0` `margin` prop was renamed to `gap`, but I forgot to update the docs. Now in release `2.0.3`, documentation reflects that change.
