### ISSUE TITLE
feature request: allow to modify the next/image attributes

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [fmkra/next-gallery#3]
### What
Right now we can only modify the following of each image:
```typescript
export interface Image {
    src: string;
    aspect_ratio: number;
    alt?: string;
}
```

I'd like to be able to modify other attributes, namely the [priority](https://nextjs.org/docs/pages/api-reference/components/image#loading) because I'm loading so many images that I'd prefer to have them be `priotity={eager}` so that there is no flickering

**Comment by fmkra** [comment]
Good recommendation!

I added `nextImageProps` key to the `Image` type, which allows to customize props passed to nextjs' `<Image />` component per specific image. So for instance if you want to pass `priority={true}` to an image, the following should be added to `images` array.
```js
{
  src: '...',
  aspect_ratio: ...,
  nextImageProps: {
    priority: true
  }
}
```

Does this change satisfy your feature request?

**Comment by CamiloGarciaLaRotta** [comment]
I believe it does 👌🏼 I'll confirm when I circle back to this front :)

**Edit:** ❇️ it works! this is awesome, thanks. If its not documented I think a small note on the Readme would be super helpful

**Comment by fmkra** [comment]
I've updated the docs already, so I'm closing this issue
